### PR TITLE
Added loan option, with fixed repay amount.

### PR DESCRIPTION
**Pull request by rdavid66**

### CODE REVIEW

**Comment by andosandor601** [comment]
Gimme fresh game rules

**Comment by rdavid66** [comment]
> Gimme fresh game rules

https://drive.google.com/open?id=1ib1JbeBHG9VP73-gZ-LJ8nROGIc2RlcF

**Comment by andosandor601** [comment]
Missing instalments (500 eur) in field 19 or 39.

**Comment by rdavid66** [comment]
> Missing instalments (500 eur) in field 19 or 39.

going to ignore that for now

**Pull request merged**
